[package]
name = "sefr"
version = "0.1.0"
authors = ["Dmitry Narkevich <me@dmitry.lol>"]
edition = "2018"

[dependencies]
crossterm = "0.9.3"

[dependencies.tui]
version = "0.5"
default-features = false
features = ['crossterm']
