[package]
name = "sefr"
version = "0.1.0"
authors = ["Dmitry Narkevich <me@dmitry.lol>"]
edition = "2018"

[dependencies]
crossterm = { git = "https://github.com/TimonPost/crossterm" }
reqwest = "0.9"
json = "0.11"
webbrowser = "0.5"
